version: '3.8'

services:
  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    # depends_on:
    #   - backend

  # backend:
  #   build:
  #     context: ./donet
  #     dockerfile: Dockerfile
  #   ports:
  #     - '5000:5000'
