name: CD to VPS

on:
  workflow_run:
    workflows: ["Build React + .NET App"]
    types:
      - completed
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }} 
        port: 22
        script: | 
          cd /home/azureuser/vps_dotnet_reactjs
          git config --global --add safe.directory /home/azureuser/vps_dotnet_reactjs
          git reset --hard
          git stash -u
          git pull origin main
          git stash pop
          git config pull.rebase false
          sudo docker-compose down
          sudo docker-compose up -d --build
