name: CD to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }} 
        port: 22
        script: |
          cd /home/azureuser/vps_dotnet_reactjs
          git reset --hard
          git pull origin main
          git config pull.rebase false  # Thêm dòng này để xử lý các nhánh phân kỳ
          sudo usermod -aG docker azureuser  # Thêm tài khoản vào nhóm Docker
          sudo docker-compose down
          sudo docker-compose up -d --build
