name: CD to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }} 
        port: 22
        script: | 
          sudo su
          cd vps_dotnet_reactjs
          git reset --hard  # Separate git reset command
          git stash -u
          git pull origin main
          git stash pop
          git config pull.rebase false 
          docker-compose down
          docker-compose up -d --build
