name: Deploy to VPS

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/azureuser/vps_dotnet_reactjs/vps/vps_dotnet_reactjs
            git reset --hard
            git pull origin production
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
